export const ORDER_STATUS = {
  PENDING: "PENDING",
  OPEN: "OPEN",
  FILLED: "FILLED",
  PARTIALLY_FILLED: "PARTIALLY_FILLED",
  CANCELLED: "CANCELLED",
  REJECTED: "REJECTED",
};

export const ORDER_STATUS_TRANSITIONS = {
  PENDING: [
    ORDER_STATUS.OPEN,
    ORDER_STATUS.CANCELLED,
    ORDER_STATUS.REJECTED,
  ],

  OPEN: [
    ORDER_STATUS.PARTIALLY_FILLED,
    ORDER_STATUS.FILLED,
    ORDER_STATUS.CANCELLED,
  ],

  PARTIALLY_FILLED: [
    ORDER_STATUS.FILLED,
    ORDER_STATUS.CANCELLED,
  ],

  FILLED: [],

  CANCELLED: [],

  REJECTED: [],
};